FROM ubuntu AS builder
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /src
ADD . .
RUN apt-get update && apt-get install -y build-essential cmake ninja-build git python \
&& cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
&& cd build && ninja
FROM ubuntu
COPY --from=builder /src/build/main/tinybooter /usr/bin/tinybooter
